
// >>> paste right after buildscript { ... } in android/build.gradle (top-level)
subprojects {
    project.configurations.all {
        resolutionStrategy {
            // byte-buddy version compatible with JDK 17
            force "net.bytebuddy:byte-buddy:1.12.23"
            // bouncycastle version compatible with JDK 17
            force "org.bouncycastle:bcprov-jdk18on:1.74"
        }
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
    }
}



rootProject.buildDir = "../build"


subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
// The below script
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}
// till here
subprojects {
    project.evaluationDependsOn(':app')
}



tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
